import type { Issue, ReviewResult, Severity } from "../types.js";
import {
  aiModeLabel,
  countBySeverity,
  describeTarget,
  formatDuration,
  groupByFile,
  plural,
  sanitize,
  SEVERITIES,
} from "./common.js";

const LABEL: Record<Severity, string> = { critical: "Critical", warning: "Warning", suggestion: "Suggestion" };

/** Escapes text for inline use in HTML/table contexts. */
function inline(text: string): string {
  return sanitize(text)
    .replace(/\n+/g, " ")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\|/g, "\\|");
}

function code(text: string): string {
  const clean = sanitize(text).replace(/\n+/g, " ");
  const longest = Math.max(0, ...(clean.match(/`+/g) ?? []).map((m) => m.length));
  const fence = "`".repeat(longest + 1);
  const pad = clean.startsWith("`") || clean.endsWith("`") ? " " : "";
  return `${fence}${pad}${clean}${pad}${fence}`;
}

function fenced(body: string, lang: string): string {
  const longest = Math.max(2, ...(body.match(/`{3,}/g) ?? []).map((m) => m.length));
  const fence = "`".repeat(longest + 1);
  return `${fence}${lang}\n${body.replace(/\n$/, "")}\n${fence}`;
}

function summaryTable(result: ReviewResult): string[] {
  const rows = groupByFile(result.issues).map(([file, issues]) => {
    const counts = countBySeverity(issues);
    return `| ${code(file).replace(/\|/g, "\\|")} | ${SEVERITIES.map((s) => counts[s] || "").join(" | ")} |`;
  });
  const totals = countBySeverity(result.issues);
  return [
    `| File | ${SEVERITIES.map((s) => LABEL[s]).join(" | ")} |`,
    "|---|---:|---:|---:|",
    ...rows,
    `| **Total** | ${SEVERITIES.map((s) => `**${totals[s]}**`).join(" | ")} |`,
  ];
}

function issueBlock(issue: Issue): string[] {
  const where = issue.line === null ? "file" : `L${issue.line}${issue.endLine && issue.endLine > issue.line ? `-L${issue.endLine}` : ""}`;
  const open = issue.severity === "critical" ? " open" : "";
  const lines = [
    `<details${open}>`,
    `<summary><b>${LABEL[issue.severity]}</b> · ${where} · ${inline(issue.title)}</summary>`,
    "",
  ];
  if (issue.message.trim()) lines.push(sanitize(issue.message).trim(), "");
  if (issue.suggestion?.trim()) lines.push(`**Suggestion:** ${sanitize(issue.suggestion).trim()}`, "");
  if (issue.fix) lines.push(fenced(sanitize(issue.fix.replacement), "suggestion"), "");
  const meta = [`id: ${code(issue.id)}`];
  if (issue.ruleId) meta.push(`rule: ${code(issue.ruleId)}`);
  meta.push(`source: ${issue.source}`);
  lines.push(`<sub>${meta.join(" · ")}</sub>`, "</details>", "");
  return lines;
}

export function formatMarkdown(result: ReviewResult): string {
  const { stats } = result;
  const counts = countBySeverity(result.issues);
  const out: string[] = [`### acr review: ${describeTarget(result.target)}`, ""];

  const meta = [
    `${stats.filesReviewed}/${stats.filesInDiff} files reviewed`,
    stats.provider ? `${stats.provider}${stats.model ? ` ${code(stats.model)}` : ""}` : aiModeLabel(result),
    formatDuration(stats.durationMs),
  ];
  const headline = result.issues.length
    ? `**${plural(result.issues.length, "issue")}** (${SEVERITIES.map((s) => `${counts[s]} ${s}`).join(", ")})`
    : "**No issues found**";
  out.push(`${headline} · ${meta.join(" · ")}`, "");

  if (!result.complete) {
    out.push("> [!WARNING]", "> **Review incomplete**: the results may be partial.");
    for (const err of result.errors) {
      out.push(`> - [${err.stage}]${err.file ? ` ${code(err.file)}:` : ""} ${inline(err.message)}`);
    }
    out.push("");
  } else if (result.errors.length) {
    out.push("> [!NOTE]");
    for (const err of result.errors) {
      out.push(`> - [${err.stage}]${err.file ? ` ${code(err.file)}:` : ""} ${inline(err.message)}`);
    }
    out.push("");
  }

  if (!result.issues.length) return out.join("\n").trimEnd();

  out.push(...summaryTable(result), "");
  for (const [file, issues] of groupByFile(result.issues)) {
    out.push(`#### ${code(file)}`, "");
    for (const issue of issues) out.push(...issueBlock(issue));
  }
  out.push("<sub>Generated by acr. False positive? `acr ignore <id>`</sub>");
  return out.join("\n");
}
